import { existsSync } from 'node:fs';
import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { parse as parseYaml } from 'yaml';
import { z } from 'zod';

/**
 * Wire the governed skills into the AI assistants developers actually use.
 *
 * `.governance/skills/` is not a path Claude Code or Copilot scans, so without
 * this the standards are present in the repo and invisible to the tools writing
 * most of the code. Each assistant only reads its own conventions:
 *
 *   Claude Code   .claude/skills/<slug>/SKILL.md   (auto-discovered)
 *                 CLAUDE.md                        (always loaded)
 *   Copilot       .github/copilot-instructions.md  (repo-wide)
 *                 .github/instructions/*.instructions.md  (glob-scoped)
 *
 * Everything written here is GENERATED from the hash-verified originals and is
 * regenerated on every init/sync. The originals stay the single source of truth;
 * these are projections of them.
 */

export const AssistantsConfigSchema = z
  .object({
    claude: z.boolean().default(true),
    copilot: z.boolean().default(true),
  })
  .default({});
export type AssistantsConfig = z.infer<typeof AssistantsConfigSchema>;

export const GENERATED_HEADER =
  'Generated by govctl from .governance/skills — do not edit. Run `govctl sync` to update.';

export const CLAUDE_MD = 'CLAUDE.md';
export const CLAUDE_SKILLS_DIR = join('.claude', 'skills');
export const COPILOT_INSTRUCTIONS = join('.github', 'copilot-instructions.md');
export const COPILOT_INSTRUCTIONS_DIR = join('.github', 'instructions');

const BEGIN = '<!-- BEGIN GOVERNED SKILLS (managed by govctl) -->';
const END = '<!-- END GOVERNED SKILLS (managed by govctl) -->';

export interface GovernedSkill {
  slug: string;
  name: string;
  description: string;
  /** Glob for Copilot's `applyTo`; defaults to TypeScript sources. */
  applyTo: string;
  body: string;
  raw: string;
}

export async function readAssistantsConfig(registryDir: string): Promise<AssistantsConfig> {
  const path = join(registryDir, 'registry.json');
  if (!existsSync(path)) return AssistantsConfigSchema.parse({});
  const raw = JSON.parse(await readFile(path, 'utf8')) as { assistants?: unknown };
  const parsed = AssistantsConfigSchema.safeParse(raw.assistants ?? {});
  if (!parsed.success) {
    throw new Error(`invalid "assistants" block in registry.json: ${parsed.error.issues[0]?.message}`);
  }
  return parsed.data;
}

export async function loadGovernedSkills(governanceDir: string): Promise<GovernedSkill[]> {
  const skillsDir = join(governanceDir, 'skills');
  if (!existsSync(skillsDir)) return [];

  const slugs = (await readdir(skillsDir, { withFileTypes: true }))
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();

  const skills: GovernedSkill[] = [];
  for (const slug of slugs) {
    const path = join(skillsDir, slug, 'SKILL.md');
    if (!existsSync(path)) continue;
    skills.push(parseSkill(slug, await readFile(path, 'utf8')));
  }
  return skills;
}

export function parseSkill(slug: string, raw: string): GovernedSkill {
  const match = /^---\n([\s\S]*?)\n---\n?([\s\S]*)$/.exec(raw);
  if (!match) {
    return {
      slug,
      name: slug,
      description: '',
      applyTo: '**/*.ts, **/*.tsx',
      body: raw.trim(),
      raw,
    };
  }

  const frontmatter = (parseYaml(match[1] ?? '') ?? {}) as {
    name?: string;
    description?: string;
    metadata?: { applyTo?: string };
  };

  return {
    slug,
    name: frontmatter.name ?? slug,
    description: frontmatter.description ?? '',
    applyTo: frontmatter.metadata?.applyTo ?? '**/*.ts, **/*.tsx',
    body: (match[2] ?? '').trim(),
    raw,
  };
}

export interface AssistantWriteResult {
  claudeSkills: number;
  copilotInstructions: number;
  claudeMd: 'written' | 'updated' | 'unchanged' | 'skipped';
}

export async function generateAssistantFiles(
  projectRoot: string,
  governanceDir: string,
  config: AssistantsConfig,
): Promise<AssistantWriteResult> {
  const skills = await loadGovernedSkills(governanceDir);
  const result: AssistantWriteResult = {
    claudeSkills: 0,
    copilotInstructions: 0,
    claudeMd: 'skipped',
  };
  if (skills.length === 0) return result;

  if (config.claude) {
    const dir = join(projectRoot, CLAUDE_SKILLS_DIR);
    // Wipe first: a skill removed upstream must disappear here too, or the
    // assistant keeps teaching a rule the org has retired.
    await rm(dir, { recursive: true, force: true });
    for (const skill of skills) {
      await mkdir(join(dir, skill.slug), { recursive: true });
      await writeFile(join(dir, skill.slug, 'SKILL.md'), renderClaudeSkill(skill), 'utf8');
      result.claudeSkills++;
    }
    result.claudeMd = await updateClaudeMd(projectRoot, skills);
  }

  if (config.copilot) {
    const dir = join(projectRoot, COPILOT_INSTRUCTIONS_DIR);
    await rm(dir, { recursive: true, force: true });
    await mkdir(dir, { recursive: true });
    for (const skill of skills) {
      await writeFile(
        join(dir, `${skill.slug}.instructions.md`),
        renderCopilotInstruction(skill),
        'utf8',
      );
      result.copilotInstructions++;
    }
    await mkdir(join(projectRoot, '.github'), { recursive: true });
    await writeFile(join(projectRoot, COPILOT_INSTRUCTIONS), renderCopilotIndex(skills), 'utf8');
  }

  return result;
}

function renderClaudeSkill(skill: GovernedSkill): string {
  return `---
name: ${skill.name}
description: ${JSON.stringify(skill.description)}
---

<!-- ${GENERATED_HEADER} -->

${skill.body}
`;
}

function renderCopilotInstruction(skill: GovernedSkill): string {
  const description = skill.description.replace(/'/g, "''").replace(/\s+/g, ' ').trim();
  return `---
description: '${description.slice(0, 480)}'
applyTo: '${skill.applyTo}'
---

<!-- ${GENERATED_HEADER} -->

${skill.body}
`;
}

function renderCopilotIndex(skills: GovernedSkill[]): string {
  const lines = [
    `<!-- ${GENERATED_HEADER} -->`,
    '',
    '# Coding standards for this repository',
    '',
    'These standards are centrally governed. They are enforced on every pull request:',
    'violations fail the `governance-patterns` and `governance-semantic` checks, so code',
    'that ignores them cannot merge.',
    '',
    'Detailed, file-scoped rules live in `.github/instructions/`. In summary:',
    '',
  ];

  for (const skill of skills) {
    lines.push(`## ${skill.name}`, '', skill.description, '');
  }

  lines.push(
    '---',
    '',
    'These instruction files are generated from `.governance/`, which is verified by hash',
    'on every pull request. Editing them does not change what merges — it only makes the',
    'suggestions disagree with the rules that are actually enforced, and `govctl sync`',
    'overwrites them anyway. To change a standard, open a pull request against the',
    'governance registry.',
    '',
  );
  return lines.join('\n');
}

/**
 * Insert (or refresh) a marker-delimited block in CLAUDE.md, leaving anything a
 * project wrote itself untouched.
 */
async function updateClaudeMd(
  projectRoot: string,
  skills: GovernedSkill[],
): Promise<'written' | 'updated' | 'unchanged'> {
  const path = join(projectRoot, CLAUDE_MD);
  const block = [
    BEGIN,
    '',
    '## Coding standards (governed — enforced on every PR)',
    '',
    'This project follows centrally managed standards. The full rules are loaded as',
    'skills from `.claude/skills/`; read the relevant one before writing code.',
    '',
    ...skills.map((s) => `- **${s.name}** — ${s.description}`),
    '',
    'Do not edit `.governance/`. It is verified by hash on every pull request and local',
    'edits are rejected at merge time.',
    '',
    '`.claude/skills/` and `.github/instructions/` are generated projections of it. They',
    'are not verified, so editing them changes nothing about what merges — it only makes',
    'the assistant\'s advice disagree with the rules that are actually enforced. Both are',
    'overwritten by `govctl sync`.',
    '',
    END,
  ].join('\n');

  if (!existsSync(path)) {
    await writeFile(path, `# ${'CLAUDE.md'}\n\n${block}\n`, 'utf8');
    return 'written';
  }

  const current = await readFile(path, 'utf8');
  const start = current.indexOf(BEGIN);
  const end = current.indexOf(END);

  if (start === -1 || end === -1) {
    await writeFile(path, `${current.replace(/\n*$/, '\n')}\n${block}\n`, 'utf8');
    return 'updated';
  }

  const next = current.slice(0, start) + block + current.slice(end + END.length);
  if (next === current) return 'unchanged';
  await writeFile(path, next, 'utf8');
  return 'updated';
}
