import { existsSync } from 'node:fs';
import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { parse as parseYaml } from 'yaml';
import { z } from 'zod';

/**
 * Wire the governed skills into the AI assistants developers actually use.
 *
 * `.governance/skills/` is not a path Claude Code or Copilot scans, so without
 * this the standards are present in the repo and invisible to the tools writing
 * most of the code. Each assistant only reads its own conventions:
 *
 *   Claude Code   .claude/skills/<slug>/SKILL.md   (auto-discovered)
 *                 CLAUDE.md                        (always loaded)
 *   Copilot       .github/copilot-instructions.md  (repo-wide)
 *                 .github/instructions/*.instructions.md  (glob-scoped)
 *
 * Everything written here is GENERATED from the hash-verified originals and is
 * regenerated on every init/sync. The originals stay the single source of truth;
 * these are projections of them.
 */

export const AssistantsConfigSchema = z
  .object({
    claude: z.boolean().default(true),
    copilot: z.boolean().default(true),
  })
  .default({});
export type AssistantsConfig = z.infer<typeof AssistantsConfigSchema>;

export const GENERATED_HEADER =
  'Generated by govctl from .governance/skills — do not edit. Run `govctl sync` to update.';

export const CLAUDE_MD = 'CLAUDE.md';
export const CLAUDE_SKILLS_DIR = join('.claude', 'skills');
export const COPILOT_INSTRUCTIONS = join('.github', 'copilot-instructions.md');
export const COPILOT_INSTRUCTIONS_DIR = join('.github', 'instructions');

const BEGIN = '<!-- BEGIN GOVERNED SKILLS (managed by govctl) -->';
const END = '<!-- END GOVERNED SKILLS (managed by govctl) -->';

export interface GovernedSkill {
  slug: string;
  name: string;
  description: string;
  /** Glob for Copilot's `applyTo`; defaults to TypeScript sources. */
  applyTo: string;
  body: string;
  raw: string;
}

export async function readAssistantsConfig(registryDir: string): Promise<AssistantsConfig> {
  const path = join(registryDir, 'registry.json');
  if (!existsSync(path)) return AssistantsConfigSchema.parse({});
  const raw = JSON.parse(await readFile(path, 'utf8')) as { assistants?: unknown };
  const parsed = AssistantsConfigSchema.safeParse(raw.assistants ?? {});
  if (!parsed.success) {
    throw new Error(`invalid "assistants" block in registry.json: ${parsed.error.issues[0]?.message}`);
  }
  return parsed.data;
}

export async function loadGovernedSkills(governanceDir: string): Promise<GovernedSkill[]> {
  const skillsDir = join(governanceDir, 'skills');
  if (!existsSync(skillsDir)) return [];

  const slugs = (await readdir(skillsDir, { withFileTypes: true }))
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();

  const skills: GovernedSkill[] = [];
  for (const slug of slugs) {
    const path = join(skillsDir, slug, 'SKILL.md');
    if (!existsSync(path)) continue;
    skills.push(parseSkill(slug, await readFile(path, 'utf8')));
  }
  return skills;
}

export function parseSkill(slug: string, raw: string): GovernedSkill {
  const match = /^---\n([\s\S]*?)\n---\n?([\s\S]*)$/.exec(raw);
  if (!match) {
    return {
      slug,
      name: slug,
      description: '',
      applyTo: '**/*.ts, **/*.tsx',
      body: raw.trim(),
      raw,
    };
  }

  const frontmatter = (parseYaml(match[1] ?? '') ?? {}) as {
    name?: string;
    description?: string;
    metadata?: { applyTo?: string };
  };

  return {
    slug,
    name: frontmatter.name ?? slug,
    description: frontmatter.description ?? '',
    applyTo: frontmatter.metadata?.applyTo ?? '**/*.ts, **/*.tsx',
    body: (match[2] ?? '').trim(),
    raw,
  };
}

export interface AssistantWriteResult {
  claudeSkills: number;
  copilotInstructions: number;
  claudeMd: 'written' | 'updated' | 'unchanged' | 'skipped';
  /** Files left alone because the project, not govctl, wrote them. */
  preserved: string[];
  /** Generated files removed because their skill was retired upstream. */
  removed: string[];
}

export async function generateAssistantFiles(
  projectRoot: string,
  governanceDir: string,
  config: AssistantsConfig,
): Promise<AssistantWriteResult> {
  const skills = await loadGovernedSkills(governanceDir);
  const result: AssistantWriteResult = {
    claudeSkills: 0,
    copilotInstructions: 0,
    claudeMd: 'skipped',
    preserved: [],
    removed: [],
  };
  if (skills.length === 0) return result;

  const governed = new Set(skills.map((s) => s.slug));

  if (config.claude) {
    const dir = join(projectRoot, CLAUDE_SKILLS_DIR);
    await mkdir(dir, { recursive: true });

    for (const skill of skills) {
      const path = join(dir, skill.slug, 'SKILL.md');
      if (await isForeign(path)) {
        result.preserved.push(join(CLAUDE_SKILLS_DIR, skill.slug, 'SKILL.md'));
        continue;
      }
      await mkdir(join(dir, skill.slug), { recursive: true });
      await writeFile(path, renderClaudeSkill(skill), 'utf8');
      result.claudeSkills++;
    }

    // A skill retired upstream must stop being taught — but only OUR files are
    // removed. A project's own skills live in this directory too, and deleting
    // them because the governance registry does not know about them would be
    // destroying work the tool was never asked to manage.
    for (const slug of await readDirNames(dir)) {
      if (governed.has(slug)) continue;
      const path = join(dir, slug, 'SKILL.md');
      if (await isGenerated(path)) {
        await rm(join(dir, slug), { recursive: true, force: true });
        result.removed.push(join(CLAUDE_SKILLS_DIR, slug));
      }
    }

    result.claudeMd = await upsertBlock(
      join(projectRoot, CLAUDE_MD),
      renderClaudeBlock(skills),
      '# CLAUDE.md',
    );
  }

  if (config.copilot) {
    const dir = join(projectRoot, COPILOT_INSTRUCTIONS_DIR);
    await mkdir(dir, { recursive: true });

    for (const skill of skills) {
      const path = join(dir, `${skill.slug}.instructions.md`);
      if (await isForeign(path)) {
        result.preserved.push(join(COPILOT_INSTRUCTIONS_DIR, `${skill.slug}.instructions.md`));
        continue;
      }
      await writeFile(path, renderCopilotInstruction(skill), 'utf8');
      result.copilotInstructions++;
    }

    for (const file of await readDirFiles(dir)) {
      const slug = file.replace(/\.instructions\.md$/, '');
      if (!file.endsWith('.instructions.md') || governed.has(slug)) continue;
      const path = join(dir, file);
      if (await isGenerated(path)) {
        await rm(path, { force: true });
        result.removed.push(join(COPILOT_INSTRUCTIONS_DIR, file));
      }
    }

    await mkdir(join(projectRoot, '.github'), { recursive: true });
    await upsertBlock(
      join(projectRoot, COPILOT_INSTRUCTIONS),
      renderCopilotBlock(skills),
      '# Coding standards for this repository',
    );
  }

  return result;
}

/** Does this file exist and carry our generated marker? */
async function isGenerated(path: string): Promise<boolean> {
  if (!existsSync(path)) return false;
  return (await readFile(path, 'utf8')).includes(GENERATED_HEADER);
}

/** Does this file exist and NOT carry our marker — i.e. somebody else wrote it? */
async function isForeign(path: string): Promise<boolean> {
  if (!existsSync(path)) return false;
  return !(await readFile(path, 'utf8')).includes(GENERATED_HEADER);
}

async function readDirNames(dir: string): Promise<string[]> {
  if (!existsSync(dir)) return [];
  return (await readdir(dir, { withFileTypes: true }))
    .filter((e) => e.isDirectory())
    .map((e) => e.name);
}

async function readDirFiles(dir: string): Promise<string[]> {
  if (!existsSync(dir)) return [];
  return (await readdir(dir, { withFileTypes: true }))
    .filter((e) => e.isFile())
    .map((e) => e.name);
}

function renderClaudeSkill(skill: GovernedSkill): string {
  return `---
name: ${skill.name}
description: ${JSON.stringify(skill.description)}
---

<!-- ${GENERATED_HEADER} -->

${skill.body}
`;
}

function renderCopilotInstruction(skill: GovernedSkill): string {
  const description = skill.description.replace(/'/g, "''").replace(/\s+/g, ' ').trim();
  return `---
description: '${description.slice(0, 480)}'
applyTo: '${skill.applyTo}'
---

<!-- ${GENERATED_HEADER} -->

${skill.body}
`;
}

function renderCopilotBlock(skills: GovernedSkill[]): string {
  const lines = [
    BEGIN,
    '',
    '## Coding standards (governed — enforced on every PR)',
    '',
    'These standards are centrally governed. Violations fail the `governance-patterns`',
    'and `governance-semantic` checks, so code that ignores them cannot merge.',
    '',
    'Detailed, file-scoped rules live in `.github/instructions/`. In summary:',
    '',
  ];
  for (const skill of skills) lines.push(`- **${skill.name}** — ${skill.description}`);
  lines.push(
    '',
    'These files are generated from `.governance/`, which is verified by hash on every',
    'pull request. Editing them does not change what merges — it only makes the',
    'suggestions disagree with the rules that are actually enforced, and `govctl sync`',
    'overwrites them. To change a standard, open a pull request against the governance',
    'registry.',
    '',
    END,
  );
  return lines.join('\n');
}

/**
 * Insert or refresh a marker-delimited block, leaving everything the project
 * wrote around it untouched. Never truncates: a file that already exists and has
 * no markers gets the block appended, not replaced.
 */
async function upsertBlock(
  path: string,
  block: string,
  fallbackTitle: string,
): Promise<'written' | 'updated' | 'unchanged'> {
  if (!existsSync(path)) {
    await writeFile(path, `${fallbackTitle}\n\n${block}\n`, 'utf8');
    return 'written';
  }

  const current = await readFile(path, 'utf8');
  const start = current.indexOf(BEGIN);
  const end = current.indexOf(END);

  if (start === -1 || end === -1) {
    await writeFile(path, `${current.replace(/\n*$/, '\n')}\n${block}\n`, 'utf8');
    return 'updated';
  }

  const next = current.slice(0, start) + block + current.slice(end + END.length);
  if (next === current) return 'unchanged';
  await writeFile(path, next, 'utf8');
  return 'updated';
}

function renderClaudeBlock(skills: GovernedSkill[]): string {
  return [
    BEGIN,
    '',
    '## Coding standards (governed — enforced on every PR)',
    '',
    'This project follows centrally managed standards. The full rules are loaded as',
    'skills from `.claude/skills/`; read the relevant one before writing code.',
    '',
    ...skills.map((s) => `- **${s.name}** — ${s.description}`),
    '',
    'Do not edit `.governance/`. It is verified by hash on every pull request and local',
    'edits are rejected at merge time.',
    '',
    '`.claude/skills/` and `.github/instructions/` are generated projections of it. They',
    'are not verified, so editing them changes nothing about what merges — it only makes',
    "the assistant's advice disagree with the rules that are actually enforced. Both are",
    'overwritten by `govctl sync`.',
    '',
    END,
  ].join('\n');
}
