#!/usr/bin/env bash
# Install govctl + governance-validator on this machine, before private npm exists.
#
#   bash scripts/install-local.sh [bin-dir]        # default: ~/.local/bin
#
# Writes thin shim scripts that exec the built CLIs out of this checkout. When the
# private registry is stood up, replace this with `npm i -g @shashiladev-heshan/govctl` — the
# command surface is identical, so nothing downstream changes.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN_DIR="${1:-$HOME/.local/bin}"

echo "› building packages"
(cd "$ROOT" && npm install --silent && npm run build --silent)

mkdir -p "$BIN_DIR"

write_shim() {
  local name="$1" entry="$2"
  cat > "$BIN_DIR/$name" <<EOF
#!/usr/bin/env bash
# Generated by governance/scripts/install-local.sh — dev install, not a release.
exec node "$ROOT/$entry" "\$@"
EOF
  chmod +x "$BIN_DIR/$name"
  echo "✔ $BIN_DIR/$name"
}

write_shim govctl packages/govctl/dist/index.js
write_shim governance-validator packages/validator-agent/dist/index.js

echo
if ! printf '%s' ":$PATH:" | grep -q ":$BIN_DIR:"; then
  echo "! $BIN_DIR is not on your PATH. Add it:"
  echo "    echo 'export PATH=\"$BIN_DIR:\$PATH\"' >> ~/.zshrc && exec zsh"
else
  govctl --version >/dev/null && echo "govctl $(govctl --version) ready"
fi
